[project]
name = "sops"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Richard Bywater", email = "richard.bywater@vatnz.net" }
]
requires-python = ">=3.12"
dependencies = [
    "cairosvg>=2.9.0",
    "mkdocs-awesome-pages-plugin>=2.10.1",
    "mkdocs-embed-external-markdown>=3.0.2",
    "mkdocs-git-revision-date-localized-plugin>=1.5.3",
    "mkdocs-glightbox>=0.5.2",
    "mkdocs-material==9.5.17",
    "mkdocs-redirects>=1.2.3",
    "pillow>=12.3.0",
    "urllib3<2.0",
]

[project.scripts]
sops = "sops:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
