name: ci
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy MkDocs
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v5
        name: Setup Python
        with:
          python-version: 3.12
      - run: pip install -r requirements.txt

      - name: Deploy 
        run: mkdocs gh-deploy --force --config-file production.yml
